[tool.poetry]
name = "planov4"
version = "0.2.0"
description = ""
authors = ["Rafael Ferreira Torres <rafelt444@gmail.com>"]
requires-python = ">=3.11"
dependencies = [
    "pandas==2.2.3",
    "poetry==1.8.4",
]
